# Generated by Django 2.1.2 on 2021-01-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsysVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysName', models.CharField(max_length=30)),
                ('itemName1', models.CharField(blank=True, max_length=30)),
                ('itemName2', models.CharField(blank=True, max_length=30)),
                ('itemName3', models.CharField(blank=True, max_length=30)),
                ('itemName4', models.CharField(blank=True, max_length=30)),
                ('itemName5', models.CharField(blank=True, max_length=30)),
                ('chaValue1', models.CharField(blank=True, max_length=30)),
                ('chaValue2', models.CharField(blank=True, max_length=30)),
                ('chaValue3', models.CharField(blank=True, max_length=30)),
                ('chaValue4', models.CharField(blank=True, max_length=30)),
                ('chaValue5', models.CharField(blank=True, max_length=30)),
                ('chaValue6', models.CharField(blank=True, max_length=30)),
                ('chaValue7', models.CharField(blank=True, max_length=30)),
                ('chaValue8', models.CharField(blank=True, max_length=30)),
                ('chaValue9', models.CharField(blank=True, max_length=30)),
                ('chaValue10', models.CharField(blank=True, max_length=30)),
                ('intValue1', models.IntegerField(blank=True, default=0)),
                ('intValue2', models.IntegerField(blank=True, default=0)),
                ('intValue3', models.IntegerField(blank=True, default=0)),
                ('intValue4', models.IntegerField(blank=True, default=0)),
                ('intValue5', models.IntegerField(blank=True, default=0)),
                ('intValue6', models.IntegerField(blank=True, default=0)),
                ('intValue7', models.IntegerField(blank=True, default=0)),
                ('intValue8', models.IntegerField(blank=True, default=0)),
                ('intValue9', models.IntegerField(blank=True, default=0)),
                ('intValue10', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
