# Generated by Django 2.1.2 on 2021-01-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmwsys', '0002_auto_20210119_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msysval',
            name='char_value1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value10',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value5',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value6',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value7',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value8',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='char_value9',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='item_name1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='item_name2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='item_name3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='item_name4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='item_name5',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='sys_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
