# Generated by Django 2.1.2 on 2021-01-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmwsys', '0003_auto_20210119_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msysval',
            name='item_name1',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='msysval',
            name='item_name2',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
    ]
