version: '3.6'

services:

  db: 
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bmw
      - POSTGRES_USER=bmw
      - POSTGRES_PASSWORD=bmw
    volumes:
      - ./db-datadir:C:\Program Files (x86)\PostgreSQL\9.2\data

  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
