# Generated by Django 2.1.2 on 2021-05-26 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(help_text='納期を入力してください。', verbose_name='納期')),
                ('do', models.TextField(help_text='DOを入力してください。', verbose_name='DO内容')),
                ('complete', models.CharField(max_length=1, verbose_name='完了')),
                ('user_id', models.CharField(max_length=30, verbose_name='ユーザID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='作業日を入力してください。', verbose_name='作業日時')),
                ('work_time', models.CharField(blank=True, help_text='作業時刻を入力してください。', max_length=4, null=True, verbose_name='作業時刻')),
                ('todo', models.TextField(help_text='TODOを入力してください。', verbose_name='TODO内容')),
                ('do_key', models.IntegerField(help_text='DOは必ず登録してください。')),
                ('complete', models.CharField(max_length=1, verbose_name='完了')),
                ('user_id', models.CharField(max_length=30, verbose_name='ユーザID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('create_pg_id', models.CharField(blank=True, max_length=30)),
                ('create_user_id', models.CharField(blank=True, max_length=6)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新日時')),
                ('update_pg_id', models.CharField(blank=True, max_length=30)),
                ('update_user_id', models.CharField(blank=True, max_length=6)),
            ],
        ),
    ]
