# Generated by Django 2.1.2 on 2021-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttodo',
            name='row',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tdo',
            name='delivery_date',
            field=models.DateField(verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='tdo',
            name='do',
            field=models.TextField(verbose_name='DO内容'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='complete',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='完了'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='do_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='todo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TODO内容'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ユーザID'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='work_date',
            field=models.DateField(blank=True, null=True, verbose_name='作業日時'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='work_time',
            field=models.CharField(max_length=4, verbose_name='作業時刻'),
        ),
    ]
