# Generated by Django 2.1.2 on 2021-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210528_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdo',
            name='complete',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='完了'),
        ),
        migrations.AlterField(
            model_name='tdo',
            name='do',
            field=models.CharField(max_length=100, verbose_name='DO内容'),
        ),
        migrations.AlterField(
            model_name='tdo',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ユーザID'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='row',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='work_time',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='作業時刻'),
        ),
    ]
