# Generated by Django 2.1.2 on 2021-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210531_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdo',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tdo',
            name='do',
            field=models.CharField(max_length=256, verbose_name='DO内容'),
        ),
        migrations.AlterField(
            model_name='tdo',
            name='update_user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='todo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='TODO内容'),
        ),
        migrations.AlterField(
            model_name='ttodo',
            name='update_user_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
