# Generated by Django 2.1.2 on 2024-02-13 03:11

from django.db import migrations, models
import django.utils.timezone
import estimates.models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='delevery_receipt',
            field=models.FileField(blank=True, upload_to=estimates.models.placing_upload_to, verbose_name='納品書'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='delivery_date',
            field=models.DateField(blank=True, verbose_name='納品日'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='description',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_delivary_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_files',
            field=models.FileField(blank=True, upload_to=estimates.models.estimate_upload_to, verbose_name='見積書'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_man_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='工数'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_type',
            field=models.CharField(blank=True, choices=[('rough', '概算'), ('formal', '正式')], max_length=20, verbose_name='概算・見積'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_unit',
            field=models.CharField(blank=True, choices=[('man_month', '人月'), ('man_date', '人日'), ('man_hour', '時間')], max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='expected_delivery_date',
            field=models.DateField(blank=True, verbose_name='納品予定日'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='expected_inspection_date',
            field=models.DateField(blank=True, verbose_name='検収予定日'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='go_live_date',
            field=models.DateField(blank=True, verbose_name='本稼働日'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='inspection_date',
            field=models.DateField(blank=True, verbose_name='検収日'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='inspection_receipt',
            field=models.FileField(blank=True, upload_to=estimates.models.placing_upload_to, verbose_name='検収書'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='quotation',
            field=models.FileField(blank=True, upload_to=estimates.models.placing_upload_to, verbose_name='見積書'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='received_date',
            field=models.DateField(blank=True, verbose_name='受注日'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='rouph_estimate_delivary_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='納期'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='rouph_estimate_man_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='工数'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='rouph_estimate_unit',
            field=models.CharField(blank=True, choices=[('man_month', '人月'), ('man_date', '人日'), ('man_hour', '時間')], max_length=20, verbose_name=''),
        ),
    ]
