# Generated by Django 2.1.2 on 2024-02-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_auto_20240213_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='quotation_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='見積提示時期'),
        ),
    ]
