# Generated by Django 2.1.2 on 2024-02-16 03:43

from django.db import migrations, models
import estimates.models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_estimate_quotation_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='estimate_type',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='estimate',
            name='rouph_estimate_files',
            field=models.FileField(blank=True, null=True, upload_to=estimates.models.estimate_upload_to, verbose_name='概算見積書'),
        ),
    ]
