# Generated by Django 2.1.2 on 2021-02-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmpFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, max_length=256)),
                ('attach', models.FileField(upload_to='Files/', verbose_name='添付ファイル')),
            ],
        ),
    ]
