# Generated by Django 2.1.2 on 2021-02-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpfile',
            name='attach',
            field=models.FileField(upload_to='', verbose_name='添付ファイル'),
        ),
    ]
