# Generated by Django 2.1.2 on 2021-02-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbk', '0002_auto_20210202_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpfile',
            name='attach',
            field=models.BinaryField(),
        ),
    ]
